# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "D:/Razno/unitree_go2/cyclonedds-cxx-master;D:/Razno/unitree_go2/cyclonedds-cxx-master")
set(CPACK_CMAKE_GENERATOR "Visual Studio 17 2022")
set(CPACK_COMPONENTS_ALL "dev;lib;idlcxx")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEV_DESCRIPTION "Development files for use with Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_COMPONENT_DEV_DISPLAY_NAME "Eclipse Cyclone DDS ISO IEC C++ PSM development")
set(CPACK_COMPONENT_IDLCXX_DESCRIPTION "Idl compiler plugin library for Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_COMPONENT_IDLCXX_DISPLAY_NAME "Eclipse Cyclone DDS ISO IEC C++ PSM compiler plugin for idlc")
set(CPACK_COMPONENT_LIB_DESCRIPTION "Library used to run programs with Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_COMPONENT_LIB_DISPLAY_NAME "Eclipse Cyclone DDS ISO IEC C++ PSM library")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CycloneDDS-CXX built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "WIX;ZIP;")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "D:/Razno/unitree_go2/cyclonedds-cxx-master;CycloneDDS-CXX;ALL;/")
set(CPACK_INSTALL_PREFIX "D:/Razno/unitree_go2/install")
set(CPACK_MODULE_PATH "D:/Razno/unitree_go2/cyclonedds-cxx-master/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "D:/Razno/unitree_go2/cyclonedds-cxx-master/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "https://github.com/eclipse-cyclonedds/cyclonedds-cxx")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_PACKAGE_FILE_NAME "CycloneDDS-CXX-0.11.0-win64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Eclipse Cyclone DDS ISO IEC C++ PSM")
set(CPACK_PACKAGE_NAME "CycloneDDS-CXX")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Eclipse Cyclone DDS project")
set(CPACK_PACKAGE_VERSION "0.11.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "11")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "D:/Razno/unitree_go2/cyclonedds-cxx-master/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-4.1/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/Razno/unitree_go2/cyclonedds-cxx-master/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_CMAKE_PACKAGE_REGISTRY "CycloneDDS-CXX")
set(CPACK_WIX_EXTRA_SOURCES "D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/PathDlg.wxs;D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/DialogOrder.wxs")
set(CPACK_WIX_LICENSE_RTF "D:/Razno/unitree_go2/cyclonedds-cxx-master/LICENSE.rtf")
set(CPACK_WIX_PATCH_FILE "D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/env.xml")
set(CPACK_WIX_PRODUCT_ICON "D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/icon.ico")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_WIX_UI_BANNER "D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/banner.png")
set(CPACK_WIX_UI_DIALOG "D:/Razno/unitree_go2/cyclonedds-cxx-master/WiX/dialog.png")
set(CPACK_WIX_UI_REF "CustomUI_InstallDir")
set(CPACK_WIX_UPGRADE_GUID "0D106C1A-D499-4DD4-ABD5-BE77415C1E8B")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/Razno/unitree_go2/cyclonedds-cxx-master/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
